### ISSUE TITLE
Hide block when 0% in the dashboard

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#1]
Hi,

I find better that the blocks are hidden (or less visible) when they display 0% for the states which not OK. This is just my opinion O :-)

**Comment by nook24** [comment]
What do you thing about make the blocks gray, like the `Service summary`?

Just as an example, I created quickly with the browsers dev tools:
<img width="1178" alt="bildschirmfoto 2017-08-30 um 19 09 33" src="https://user-images.githubusercontent.com/9019992/29885400-ef458248-8db6-11e7-8fd3-cd78903d794e.png">

**Comment by duylong** [comment]
I prefer to hide unnecessary things, gray color makes the interface sad^^

**Comment by nook24** [comment]
Done, with 3.0.1, and also deployed on https://demo.statusengine.org

**Comment by duylong** [comment]
Super, I find it more effective for reaction.
