### ISSUE TITLE
[CSS Issue] Fix labels in collapsed menu

### ISSUE THREAD

**Issue by nook24** [statusengine/interface#17]
If the main menu of Statusengine Ui gets collapsed, only one label is shown in mouse over:
![menu_col](https://user-images.githubusercontent.com/9019992/46585939-be741e00-ca77-11e8-9fda-c17f62382ecc.png)
Would be great if all labels are visible, even if the menu is collapsed, like in "normal menu" mode:
![menu_status](https://user-images.githubusercontent.com/9019992/46585955-e499be00-ca77-11e8-9637-78e1d9bc72d9.PNG)

Statusengine UI is based on [AdminLTE](https://github.com/almasaeed2010/AdminLTE).

Online demo: https://demo.statusengine.org

---
### Setup Statusengine Ui on Ubuntu 18.04 (Quick start)
(Just copy and past all commands to a plain Ubuntu box)

Install dependencies
Run all comands as `root` or via `sudo`
````
apt-get update
apt-get install git php-cli php-zip php-mysql php-ldap php-json mysql-server curl wget

curl -o composer-setup.php  https://getcomposer.org/installer
php composer-setup.php
cp composer.phar /usr/local/bin/composer
````

Load MySQL Demo Database (35KB)
Create MySQL User: (run the command `mysql`):
````SQL
CREATE USER 'statusengine'@'localhost' IDENTIFIED BY 'password';
CREATE DATABASE IF NOT EXISTS `statusengine` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON `statusengine`.* TO 'statusengine'@'localhost';
````
Import Data
````
wget https://statusengine.org/hacktoberfest/statusengine.sql

mysql -u statusengine -ppassword statusengine < statusengine.sql
````

Install Statusengine Ui
````
git clone https://github.com/statusengine/interface.git
cd interface/
chmod +x bin/*
composer install
````

Load default config file (database settings and so on)
````
wget https://statusengine.org/hacktoberfest/config.yml
mv config.yml etc/
````

Start PHP build-in web server
````
php -S 0.0.0.0:80 -t ./public
````

Browse to webinterface:
````
http://<ip-address>:80/
````

You areready to rock!
![ready](https://user-images.githubusercontent.com/9019992/46586002-83261f00-ca78-11e8-8850-67fcf1510c89.PNG)

---

Full installation guide for different distributions:
https://statusengine.org/ui/#installation

**Comment by codegagan** [comment]
is this pure CSS issue ?

**Comment by nook24** [comment]
@codegagan, i am not sure, because the AdminLTE template itself, also only show one badge.

You can see this in the demo: https://adminlte.io/themes/AdminLTE/index2.html with the `Mailbox` menu record.

This is the code for one menu record in Statusengine UI. Si i guess it is CSS related...
https://github.com/statusengine/interface/blob/e919a74f6244e3e250f8ea36757e63b5b565c0e2/public/index.html#L203-L219

**Comment by nook24** [comment]
Resolved by https://github.com/statusengine/interface/pull/29
