### ISSUE TITLE
[Docker] Create Dockerfile / Docker Compose

### ISSUE THREAD

**Issue by nook24** [statusengine/interface#18]
Would be great to have a Docker container for Statusengine UI. This would help new developers to join more easily, speed up testing and deployment.

Unfortunately I am not very familiar with docker right now...

Statusengine UI dependencies:
 - php7
 - nginx or apache
 - mysql-server

#### Need and Statusengine Ui instance to play around?
Setup Statusengine Ui on Ubuntu 18.04 (Quick start)

Install dependencies
Run all comands as `root` or via `sudo`
````
apt-get update
apt-get install git php-cli php-zip php-mysql php-ldap php-json mysql-server curl wget

curl -o composer-setup.php  https://getcomposer.org/installer
php composer-setup.php
cp composer.phar /usr/local/bin/composer
````

Load MySQL Demo Database (35KB)
Create MySQL User: (run the command `mysql`):
````SQL
CREATE USER 'statusengine'@'localhost' IDENTIFIED BY 'password';
CREATE DATABASE IF NOT EXISTS `statusengine` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON `statusengine`.* TO 'statusengine'@'localhost';
````
Import Data
````
wget https://statusengine.org/hacktoberfest/statusengine.sql

mysql -u statusengine -ppassword statusengine < statusengine.sql
````

Install Statusengine Ui
````
git clone https://github.com/statusengine/interface.git
cd interface/
chmod +x bin/*
composer install
````

Load default config file (database settings and so on)
````
wget https://statusengine.org/hacktoberfest/config.yml
mv config.yml etc/
````

Start PHP build-in web server
````
php -S 0.0.0.0:80 -t ./public
````

Browse to webinterface:
````
http://<ip-address>:80/
````

You are ready to rock!

---

Full installation guide for different distributions:
https://statusengine.org/ui/#installation

**Comment by mrala** [comment]
@nook24 I took a shot at this in #19
