### ISSUE TITLE
Add last refresh

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#2]
Hi,

Add a way to know that the page is not blocked (network problem ...) and avoid having obsolete information.

**Comment by nook24** [comment]
So, you do not like the "Lost connection to API" overlay? :(
![se_connection_lost](https://user-images.githubusercontent.com/9019992/29937039-85a315b6-8e84-11e7-8126-5386728df9a6.gif)

**Comment by duylong** [comment]
Aaah, sorry I had not yet met the problem, it was a suggestion.
