### ISSUE TITLE
Nagios Users/Group Auth

### ISSUE THREAD

**Issue by fredericksimon** [statusengine/interface#26]
Hello,

Can you add relation between UI users and Nagios Contacts/Groups ?

User 1 -  hostgroup 1
User 2 - hostgroup 1
User 3 - hostgroup  1 & 2

for example :
When **Users 1** or **2** is connected in UI, they access only **hostgroup 1**
When **Users 3** is connected, he access **hostgroup 1 & 2**

Sorry for my poor english :-) but your project is very nice.

**Comment by nook24** [comment]
Hi @fredericksimon,
at the moment the Statusengine Worker does not save object configurations (like hostgroups, contacts, hosts, services and so on) to the database anymore.
This was done in [Statusengine V2](https://statusengine.org/oldstable/documentation.php#legacy-mode) but removed with Statusengine 3.

Maybe this will come back some day, but I don't promise. For this reason it is not possible to link Nagios/Naemon Contacts to Ui Users. The Ui simply don't know which Contacts and Hostgroups exists. In addition, implementing user roles and permissions is a hell i don't really want to go through in my spare time 🙃

If user permissions are a must have for you, you should take a look at one of the following (or any other) open source projects:
- [openITCOCKPIT](https://openitcockpit.io/) - The project I am working for as my regular Job with super detailed permissions to hosts, hostgroups, contacts, templates and so on.
- [Thruk](https://www.thruk.org/) - Active maintained project but i don't know about user permissions.
- [NEMS Linux](https://nemslinux.com/) - Made for Raspberry Pi

Hope this helps.

> Sorry for my poor english :-)

No problem. You could also write in Gearman if this helps.
> but your project is very nice.

Happy to read this! You are welcome!

**Comment by fredericksimon** [comment]
Sorry, I read message by mail not on github webpage.
Thanks for this response and I'm completly agree with you.

In this case, could the use of LDAP be suitable for my use? allow users to see only certain hosts?

**Comment by nook24** [comment]
I do not plan to implement any user permissions. For this reason i close this down.
As mentioned above the https://github.com/it-novum/openITCOCKPIT project supports user roles and permissions so you could give it a try.
