### ISSUE TITLE
[CSS] Improve style of tables on large screens

### ISSUE THREAD

**Issue by nook24** [statusengine/interface#27]
While I like the mobile look of Statusengine
![Bildschirmfoto vom 2019-10-04 16-17-08](https://user-images.githubusercontent.com/9019992/66214890-d69a6f80-e6c2-11e9-9657-267b90992a71.png)

I think tables on a desktop PC could be improved.
![desktop_tables](https://user-images.githubusercontent.com/9019992/66214978-f5990180-e6c2-11e9-9067-b313955bdea7.png)

Please also make sure to consider the night mode.
![desktop_dark](https://user-images.githubusercontent.com/9019992/66214968-f2057a80-e6c2-11e9-9fae-7b8a77be40de.png)

The tables are build using the bootstrap grid system. So no `<table></table>` is used.
https://github.com/statusengine/interface/blob/26eca483476478bceddd9f31865fb0287c5d7c04/public/templates/views/services.html#L95-L119

Statusengine UI is based on [AdminLTE](https://github.com/almasaeed2010/AdminLTE).

Online demo: https://demo.statusengine.org

---
### Setup Statusengine Ui on Ubuntu 18.04 (Quick start)
(Just copy and past all commands to a plain Ubuntu box)

Install dependencies
Run all comands as `root` or via `sudo`
````
apt-get update
apt-get install git php-cli php-zip php-mysql php-ldap php-json mysql-server curl wget

curl -o composer-setup.php  https://getcomposer.org/installer
php composer-setup.php
cp composer.phar /usr/local/bin/composer
````

Load MySQL Demo Database (35KB)
Create MySQL User: (run the command `mysql`):
````SQL
CREATE USER 'statusengine'@'localhost' IDENTIFIED BY 'password';
CREATE DATABASE IF NOT EXISTS `statusengine` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON `statusengine`.* TO 'statusengine'@'localhost';
````
Import Data
````
wget https://statusengine.org/hacktoberfest/statusengine.sql

mysql -u statusengine -ppassword statusengine < statusengine.sql
````

Install Statusengine Ui
````
git clone https://github.com/statusengine/interface.git
cd interface/
chmod +x bin/*
composer install
````

Load default config file (database settings and so on)
````
wget https://statusengine.org/hacktoberfest/config.yml
mv config.yml etc/
````

Start PHP build-in web server
````
php -S 0.0.0.0:80 -t ./public
````

Browse to webinterface:
````
http://<ip-address>:80/
````

You areready to rock!
![ready](https://user-images.githubusercontent.com/9019992/46586002-83261f00-ca78-11e8-8850-67fcf1510c89.PNG)

---

Full installation guide for different distributions:
https://statusengine.org/ui/#installation

**Comment by AdamHebby** [comment]
Is there a reason you are using the grid system for the tables rather than using bootstrap tables?

What advantages do you gain from this?

Are you opposed to switching to tables, providing no functionality is lost and it is done correctly / to your satisfaction?

**Comment by nook24** [comment]
@AdamHebby the reason why I don't want to use tables is basically because they are not responsive at all. Or at least, I was never able to get this done.

I'm not a fan about horizontal scrolling tables which always requires some [ugly javascript hacks](https://stackoverflow.com/questions/26018756/bootstrap-button-drop-down-inside-responsive-table-not-visible-because-of-scroll).

But maybe this is just due to my poor CSS skills :)

**Comment by nook24** [comment]
Many thanks to @adrienluitot for resolving this #30
