### ISSUE TITLE
Show the current ACK, DOWNTIME

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#3]
Hi,

It will be good to list in the dashboard (or elsewhere) the current ACK/DOWNTIME informations. What do you think ?

**Comment by nook24** [comment]
So, the downtime information for currently running or upcoming downtimes are available at "Upcoming downtimes":
<img width="1198" alt="bildschirmfoto 2017-09-04 um 16 57 07" src="https://user-images.githubusercontent.com/9019992/30031657-a9be5968-9192-11e7-928e-f1f7c523307f.png">

I could add a new menu record "Acknowledgements" (or so), for a list with acknowledgement informations for host and services...

**Comment by nook24** [comment]
Is this what you are looking for?

**Comment by duylong** [comment]
That's great if we have a new menu record "Acknowledgements".

It would have been nice to list the current events on the dashboard. After I'm afraid that the dashbord becomes heavy.

**Comment by nook24** [comment]
Done in the elastic branch :)
![bildschirmfoto 2017-09-13 um 23 01 10](https://user-images.githubusercontent.com/9019992/30402182-2e981da8-98dd-11e7-8355-5e7aeadfe0c2.png)

**Comment by duylong** [comment]
Can you add the current number in the menu name ? "Acknowledgements (2)" for example

**Comment by nook24** [comment]
Yep. I love the idea :)
To keep the load low, I set the auto refresh interval to 30 seconds for the menu.

![bildschirmfoto 2017-09-14 um 20 16 36](https://user-images.githubusercontent.com/9019992/30448068-00b5cb36-998e-11e7-89cb-6d0ef590848d.png)

**Comment by duylong** [comment]
Love it!

To avoid false positives, it would still be good to consider ACK / DOWNTIME in displaying CRIT / WARN. After I know that the implementation is not trivial.

**Comment by nook24** [comment]
I asked several people, and all said, that the dashboard should show critical services as critical, even if they are acknowledged or in downtime. So I will close #4.

As compromise, someone said, that the menu should only show services that are not acknowledged or in downtime. I guess this is a good solution for all of us.

**Comment by duylong** [comment]
Why not :) The behavior should be viewed in the documentation, for some people it will be a bug.

**Comment by nook24** [comment]
I added an new setting, I guess this is the best solution:
Default (show all):
![bildschirmfoto 2017-09-19 um 21 58 33](https://user-images.githubusercontent.com/9019992/30612752-e1636be8-9d85-11e7-9920-5d4f83c3d333.png)

Hide Ack and Downtime from Dashboard and menu:
![bildschirmfoto 2017-09-19 um 21 58 54](https://user-images.githubusercontent.com/9019992/30612756-e52b9a7a-9d85-11e7-9667-8c4c6c940654.png)

Require run of `composer dump-autoload` or `composer update` to work.

**Comment by duylong** [comment]
Finally the ACK / DOWN is hidden in the dashboard too?

**Comment by nook24** [comment]
Yes

**Comment by duylong** [comment]
A downtime on a host should not display CRIT / WARN for services in menu and dashboard. Naemon works like that for notifications.

**Comment by nook24** [comment]
Just schedule the downtime with `Node including services` :)

**Comment by duylong** [comment]
This is not the default behavior in Naemon ? When a downtime is created on a host, the services also have the downtime, right? In my case, service notifications are disabled.

**Comment by nook24** [comment]
Nop, if you schedule a downtime for a host, only the host is in a scheduled downtime. The services of the host are still operating normally.
When in comes to notifications, Naemon checks if notifications should be suppressed due to some reasons. Here is the code from Naemon's notification.c
````C
	/* if this service is currently in a scheduled downtime period, don't send the notification */
	if (svc->scheduled_downtime_depth > 0) {
		LOG_SERVICE_NSR(NSR_IS_SCHEDULED_DOWNTIME);
		return ERROR;
	}

	/* if this host is currently in a scheduled downtime period, don't send the notification */
	if (temp_host->scheduled_downtime_depth > 0) {
		LOG_SERVICE_NSR(NSR_SERVICE_HOST_SCHEDULED_DOWNTIME);
		return ERROR;
	}
````
https://github.com/naemon/naemon-core/blob/master/src/naemon/notifications.c#L820-L830

This is the reason, why the Statusengine Ui's default option for scheduling host downtimes is `Node including services`:
<img width="596" alt="bildschirmfoto 2017-10-12 um 18 26 05" src="https://user-images.githubusercontent.com/9019992/31507409-da930ec0-af7a-11e7-9f8f-b6cfcb2093e6.png">

**Comment by nook24** [comment]
"Current Acknowledgements" was added.
