### ISSUE TITLE
Schedule downtime and Acknowledgement is not working

### ISSUE THREAD

**Issue by emjhay2004** [statusengine/interface#33]
The Schedule downtime and Acknowledgement is not working on my installation.

NAGIOS Core 4.4.5
Installed all Statusengine pre-requisite

But still the Statusengine UI does not reflect the submitted Schedule downtime and Acknowledgement.

**Comment by nook24** [comment]
Sorry for my late response on this. Are you scheduling the downtimes through Statusengine UI?
External commands get processed by the Statusengine Worker. Please make sure that `submit_method=cmd`. `qh` is not supported by Nagios Core.
Also make sure to check that you have set the right path of the nagios.cmd in the config: `external_command_file: /opt/nagios/var/nagios.cmd`.

You can find the config options in the config.yml of the Statusengine Worker.
https://github.com/statusengine/worker/blob/master/etc/config.yml.example#L237-L248

If this is all correct please set `log_external_commands=1` in your nagios.cfg and check the log if the external command will reach Nagios Core.
