### ISSUE TITLE
need cancel downtime for host and services

### ISSUE THREAD

**Issue by Vijay8888** [statusengine/interface#34]
Hi @nook24 ,

Currently we do not have option to cancel downtime for host and services at a time.
we need to cancel downtime for each service separately. it would be great if suggest any solution.
and also when we schedule a downtime if we have option to select particular time to schedule downtime along with specific hours which we have currently. could you please suggest any possibility in code level changes.Thanks

**Comment by nook24** [comment]
Hi @Vijay8888 
I'm working on this. It will be look something like this soon:
![Bildschirmfoto vom 2020-04-06 21-01-16](https://user-images.githubusercontent.com/9019992/78595262-05e49180-784a-11ea-9846-b2e866717aaf.png)

**Comment by Vijay8888** [comment]
@nook24 Thanks that would be very helpful.

**Comment by nook24** [comment]
I also added the feature to create downtimes with a defined date and time:
![Bildschirmfoto vom 2020-04-15 21-17-52](https://user-images.githubusercontent.com/9019992/79380489-d1b35400-7f60-11ea-9f11-0c1243dbf75c.png)

Please clone the current master branch for testing.

**Comment by Vijay8888** [comment]
Thanks and it helps alot . will try this option.
