### ISSUE TITLE
Allow subpath for login

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#36]
Hi,

I have a problem when I click on the button Sign in. It redirect me to /login.html, but my real url is  /subpath/login.html

Can you add a option for this feature?

Best regards,

**Comment by nook24** [comment]
I added support for this. Unfortunately for now it is required to manually patch the file `/public/index.html`

https://github.com/statusengine/interface/blob/d81e1884e160df6bbf562da7dbd3d6df3aae15ff/public/index.html#L6-L13

For example:
```html
<base href="/statusengine/">
```
### Why is there no config option yet?
For now the index.html is a HTML file. So no PHP is available. Renaming the file to `.php` could break some web server configurations which I do not want.
Maybe I will change this with the next larger version update.

### Example Apache Config
```apache
Alias /statusengine /usr/share/interface/public

<Directory /usr/share/interface/public>
    Options SymLinksIfOwnerMatch
    DirectoryIndex index.html

    <IfModule mod_php7.c>
        php_admin_value open_basedir /usr/share/interface
    </IfModule>

</Directory>

```

**Comment by duylong** [comment]
I avoid creating an application by subdomain. I prefer to group by family of products. Thanks for the tip, it suits me too :)
