### ISSUE TITLE
Hover color missing on _commands

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#37]
Hi,

No hover color in the links of _Commands with dark mode. No problem with History ;)

**Comment by nook24** [comment]
Good catch. This was also missing in the light theme.
![hover-dark](https://user-images.githubusercontent.com/9019992/80922924-98f8e480-8d80-11ea-8422-0f5f205d0d17.jpg)

**Comment by duylong** [comment]
Tested and approved :)
