### ISSUE TITLE
Add user name after login

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#38]
Hi,

After login, information is missing to indicate that we are authenticated. The login name to the right of "Settings"?

**Comment by nook24** [comment]
Good idea
![se_no_login](https://user-images.githubusercontent.com/9019992/81338901-a8906a00-90ad-11ea-9e2e-115deb89fd02.png)
![se_loggedin](https://user-images.githubusercontent.com/9019992/81338902-a9290080-90ad-11ea-9a3b-b12f45d0f5da.png)

**Comment by duylong** [comment]
Tested and approved 👍
