### ISSUE TITLE
Disable host/service with a old last check

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#40]
Hi,

I have some workers which no longer work. Is it possible to gray out or hide (I don't know which is better) hosts/services that are obsolete (with a date of last verification below a certain threshold)

Best regards,

**Comment by nook24** [comment]
I'm not sure what you mean...

If you remove a host/service from the Naemon configuration and reload Naemon the host/services is gone from the interface (but the system stores the history in case the host or service will come back in the future)

If you want to remove a cluster node, please use the cluster CLI. It will also remove the host and services from the database, but keep the history for reports or so:
https://statusengine.org/worker/#manage-cluster-nodes

The monitoring always represents the current state. There is no support for disabled or deleted hosts. Gone is gone.

**Comment by duylong** [comment]
Strange, my statusengine interface keeps the old configurations, that's why my issue. For example, when I rename a service, the old service is still present in my interface.

When I stop a worker, these data are still visible in Statusengine, the monitoring don't represents the current state with me. 

I use Redis, MySQL and ES for datas
Naemon 1.2.0
Statusengine 3.1.0 with 3 workers

**Comment by duylong** [comment]
I deleted all my workers. It seems resolve my problem with old checks. I don't know why I still had old checks...
