### ISSUE TITLE
Issues detected on unknown status

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#43]
Hi,

I use service_skip_check_host_down_status in order to change service status to unknow when the host is down. There is no point in keeping the wrong status.

In statusengine, I see all "unknowns" in "Issues detected" while the host is in downtime. Can we ignore "unknown" when the host is ACK / DOWNTIME in "Issues detected" ?

**Comment by nook24** [comment]
Services that are in a downtime or acknowledged will not be listed as "services with issues".
You can use the [SCHEDULE_HOST_SVC_DOWNTIME](https://www.naemon.org/documentation/developer/externalcommands/schedule_host_svc_downtime.html) to schedule downtimes to all services of a host.

**Comment by duylong** [comment]
I use only SCHEDULE_HOST_DOWNTIME. I did not know that I also had to do SCHEDULE_HOST_SVC_DOWNTIME, because with dependencies and service_skip_check_host_down_status option, all the services of a host are no longer checked if the host is down.

**Comment by nook24** [comment]
Unfortunately there is nothing Statusengine can do about this. The proper way is to set a Downtime for Host + Services:

![Bildschirmfoto 2021-02-27 um 15 29 23](https://user-images.githubusercontent.com/9019992/109390258-d67ebd80-7910-11eb-8dc3-4158ce2fb631.png)


Statusengine will execute the necessary commands in the background for you:
```
statusengine-worker[28550]: Execute external command (via RabbitMq Queue): {"Command":"raw","Data":"[1614436179] SCHEDULE_HOST_DOWNTIME;winserver;1614436179;1614437079;1;0;900;admin;Down for now"}
statusengine-worker[28550]: Execute external command (via RabbitMq Queue): {"Command":"raw","Data":"[1614436179] SCHEDULE_HOST_SVC_DOWNTIME;winserver;1614436179;1614437079;1;0;900;admin;Down for now"}
```

If you need to cancel a downtime, Statusengine can also cancel the service downtimes:
![Bildschirmfoto 2021-02-27 um 15 31 29](https://user-images.githubusercontent.com/9019992/109390279-f3b38c00-7910-11eb-9eec-2517d88f5636.png)

Generated backend commands:
```
statusengine-worker[28550]: Execute external command (via RabbitMq Queue): {"Command":"raw","Data":"[1614436330] DEL_HOST_DOWNTIME;1"}
statusengine-worker[28550]: Execute external command (via RabbitMq Queue): {"Command":"raw","Data":"[1614436330] DEL_SVC_DOWNTIME;8"}
statusengine-worker[28550]: Execute external command (via RabbitMq Queue): {"Command":"raw","Data":"[1614436330] DEL_SVC_DOWNTIME;7"}
statusengine-worker[28550]: Execute external command (via RabbitMq Queue): {"Command":"raw","Data":"[1614436330] DEL_SVC_DOWNTIME;6"}
statusengine-worker[28550]: Execute external command (via RabbitMq Queue): {"Command":"raw","Data":"[1614436330] DEL_SVC_DOWNTIME;5"}
statusengine-worker[28550]: Execute external command (via RabbitMq Queue): {"Command":"raw","Data":"[1614436330] DEL_SVC_DOWNTIME;4"}
statusengine-worker[28550]: Execute external command (via RabbitMq Queue): {"Command":"raw","Data":"[1614436330] DEL_SVC_DOWNTIME;3"}
statusengine-worker[28550]: Execute external command (via RabbitMq Queue): {"Command":"raw","Data":"[1614436330] DEL_SVC_DOWNTIME;2"}
```
