### ISSUE TITLE
schedule downtime 15 min becomes 15 hours

### ISSUE THREAD

**Issue by skaynl** [statusengine/interface#45]
I have this strange problem with the statusengine-ui, if I schedule a downtime for a host for 30 min or other times (tested a few) everything works fine. But if I choose the 15 min option it's scheduling the downtime for 15 hours
![setdowntime15min](https://user-images.githubusercontent.com/3024018/85686909-ab343680-b6d0-11ea-8043-23e1a098b642.jpg)
![resultdowntime15min](https://user-images.githubusercontent.com/3024018/85686932-aec7bd80-b6d0-11ea-8ab8-701b422bbcfb.jpg)
I'm running a test environment of it all at home and there I don't have this issue. But I'm wondering if anyone can tell me where to look to solve this issue at work.

**Comment by nook24** [comment]
This got fixed a while ago: https://github.com/statusengine/interface/commit/bfbf9646e70e6608b4577d2f235f9401663fa519

Please update Statusengine UI to resolve the issue.
Docs: https://statusengine.org/ui/#how-to-update

Daniel

**Comment by skaynl** [comment]
Thanks, for the update…. Updating was the first thing I tried I going to look into it some more!

**Comment by skaynl** [comment]
I renamed the /usr/share/statusengine-ui to statusengine-ui-old to be sure I got all files anew with git clone, copied config.yml.example to config.yml and only changed use_crate: 0 and use_mysql: 1 and pasted the password from the old config.yml file.
So everything should be set to the latest files but still I get  
EXTERNAL COMMAND: SCHEDULE_HOST_SVC_DOWNTIME;**********;1593081572;1593135572;1;0;54000;admin;test 
1;0;54000 -> 1 minute from now but 54000 is still equal to 15 hours.

I tried adding a 14 min option in public/templates/modals/submitHostDowntime.html
     <option value="{{ 60 * 14}}">14 minutes</option>
     <option value="900">15 minutes</option>
just for testing but that doesn't show up in the menu... it's as if the system is working from another folder but I looked for one and couldn't find any files matching the files from /usr/share/statusengine-ui

**Comment by skaynl** [comment]
oh wtf.... colleage must have moved the folder to /var/www/html.... I found files there! the basterd :P

**Comment by skaynl** [comment]
Still with apache now pointing to the right folder (/usr/share/statuseng..) as root document folder I got the 15 hours error!
Tried this:
option value="{{ 60 * 15}}">15 minutes (1)</option
option value="900">15 minutes</option

and the 60*15 works... I'm going to remove the 900 line (in services too)

**Comment by skaynl** [comment]
is that even possible to have old code if you removed the folder and did a new git clone https://github.com/statusengine/interface.git statusengine-ui?

**Comment by nook24** [comment]
No that's not possible...

- Please make sure that you have the latest files and that your web servers document root is pointing on the same directory.
- Please check the file file on disk using vim (or any other editor) if the file contains `$scope.end = "900"`
- Also try to clear your browsers cache for force reload the interface. (`CTRL` + `SHIFT` + `R`) or `CMD` + `SHIFT` + `R` on macOS.

In addition please check if you have the `Date mode`, otherwise you run old code ^^
![date_mode](https://user-images.githubusercontent.com/9019992/85829798-b009f080-b78b-11ea-91e3-0fe758d3380e.png)

**Comment by skaynl** [comment]
git pull origin master:
From https://github.com/statusengine/interface
 * branch            master     -> FETCH_HEAD
Already up to date.

$scope.end = "900" is found in the following files (I used Midnight Commander to search)
SubmitHostDowntimeController.js
SubmitServiceDowntimeController.js

Date mode is available

and like I said I got 15 minutes working after changing the templates/models files from:
option value="900">15 minutes</option
to
option value="{{ 60 * 15}}">15 minutes</option

no idea why this corrected the problem (seeing this didn't need to be changed at home installation) but if it works I'm happy ;)

**Comment by skaynl** [comment]
sorry bit new at github, I see I can close the issue here.
