### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by thale13** [statusengine/interface#46]
Sorry if this is the wrong format/forum, but is the interface documented anywhere so I could customize/change it if I wanted to?
I can't find any sort of API or interface docs (haven't looked at the documentation project yet) and I can't find a forum or wiki or anything.  

The docs for install are awesome, by the way.

**Comment by nook24** [comment]
Hi @thale13,
Most of the work is done by myself which is one of the reasons why there is no forum. Creating a GitHub issue is perfectly fine.

The [statusengine.org](https://statusengine.org/) website lives in this repository: https://github.com/statusengine/docs

For the interface itself, there is no real API documentation at the moment. All API Endpoints are inside of [this file](https://github.com/statusengine/interface/blob/master/public/api/index.php).
Also each method has a short doc block about the available GET parameters:
https://github.com/statusengine/interface/blob/777193b15711b411bd263a72a07b2756e63237e3/public/api/index.php#L163-L175

Also the browser console is a good method to find out what requests get send to the backend. I prefer Firefox for this.
![Bildschirmfoto 2021-02-26 um 08 03 52](https://user-images.githubusercontent.com/9019992/109267082-4c97fd00-7809-11eb-8b2c-055f53c27edd.png)

But all this is a bit non-standard^^

All AngularJS States with their corresponding controller and template are defined in here:
https://github.com/statusengine/interface/blob/777193b15711b411bd263a72a07b2756e63237e3/public/js/scripts/ng.app.js#L228-L242

Hope this helps

> The docs for install are awesome, by the way.

Many thanks :)
