### ISSUE TITLE
request features

### ISSUE THREAD

**Issue by tinoklauer** [statusengine/interface#48]
Hi,

1.)
Is it possible to sort the hosts and services in groups?
In nagios we used a lot of host groups and service groups for a better overview.

2.) 
Is it possible to to implement a user control? As an example a user should log in and see the services assigned to him and their status but not more.

3.) 
Is it possible to Acknowledge issue for alle crit services on one host?

thanks

**Comment by nook24** [comment]
Short answer: No

Long answer:
>1.) Is it possible to sort the hosts and services in groups?
>2.) Is it possible to to implement a user control?...

Statusengine has no information about the object configuration, thairfore no grouping or user permissions
Please read post here for more details: https://github.com/statusengine/interface/issues/26#issuecomment-520560414

The Statusengine UI is very slim and minimalistic. The main goal of the Statusengine  project is to store Nagios/Naemon event data. The UI is more or less a goodie.

You probably should take a look at: https://github.com/it-novum/openITCOCKPIT It has all the features you are asking for in this issue and much more. 
And it's also using Statusengine under the hood.

> 3.) Is it possible to Acknowledge issue for alle crit services on one host?

This would be possible - unfortunately it is not implemented yet. It got already requested a while ago  #11

**Comment by tinoklauer** [comment]
Hallo,

ich hatte gelesen, dass ich auch auf deutsch bei dir schreiben kann =)

Danke für die Erklärung!

1.) Es würde auch gehen, wenn die Statusengine ein paar festgelegte Hostgruppen zur Verfügung stellt ohne das sie vom Monitoringsystem stammen z.B. Testsystem, Routinesystem, Backupsystem, Abnahmesystem oder 1,2,3,4 oder A,B,C,D etc.

4) Ist es möglich in der Statusengine Pfade bzw. Links für VNC oder RDP Aufrufe der Hosts zu hinterlegen? Die Idee ist, man kann auf den RDP link des Hosts klicken und Windows startet eine RDP Verbindung zum Host über die *.RDP Datei welche aufgerufen wird.

Vielleicht hilft das aus der nagios_mail.php

https://github.com/otto802/nagios_mail

Dort habe ich diese Zeilen eingefügt:

$config['rdplink']              = 'Pfad zum Ordner der RDP-Links';
$output_html[] = '<a href="'. $this->config['rdplink'] . $this->nagios['HOSTNAME'] .'.rdp'.'">' . "RDP_Link" . '</a>';

Vielen Dank

**Comment by nook24** [comment]
> 1.) Es würde auch gehen, wenn die Statusengine ein paar festgelegte Hostgruppen zur Verfügung stellt ohne das sie vom Monitoringsystem stammen z.B. Testsystem, Routinesystem, Backupsystem, Abnahmesystem oder 1,2,3,4 oder A,B,C,D etc.

Wie gesagt, dies ist etwas was es in Statusengine (wahrscheinlich) nicht geben wird.

> 4. Ist es möglich in der Statusengine Pfade bzw. Links für VNC oder RDP Aufrufe der Hosts zu hinterlegen? Die Idee ist, man kann auf den RDP link des Hosts klicken und Windows startet eine RDP Verbindung zum Host über die *.RDP Datei welche aufgerufen wird.

Das ist Möglich: https://github.com/statusengine/interface/blob/master/etc/config.yml.example#L207-L237
![external_links](https://user-images.githubusercontent.com/9019992/112895473-76c92d00-90dd-11eb-8e36-becc4c1159d3.png)

**Comment by tinoklauer** [comment]
Guten Tag,

ich habe die externen Links getestet aber anscheint mache ich etwas falsch:

ich habe die /opt/statusengine/worker/etc/config.yml wie folgt angepasst:

external_urls: 1 <-- wird das gebraucht?

 #external_url_lists:
 - name: RDP_Link
   url: \\path\$hostname$.rdp
 - name: Docs of Statusengine
   url: https://statusengine.org

systemctl restart apache2

systemctl restart statusengine ( Test, da es nicht ging)

mir werden aber keine Links angezeigt.

Habe ich etwas vergessen?

Vielen Dank

**Comment by nook24** [comment]
Du hast es in die Worker Config eingetragen, der hat damit aber nichts zu tun. Das ganze muss in die Config vom Web Interface: `/usr/share/statusengine-ui/etc/config.yml`

> external_urls: 1 <-- wird das gebraucht?

Nein, wo hast du das her?

Beispiel:
```yml
external_url_lists:
  - name: RDP_Link
    url: rdp://$hostname$
  - name: Docs of Statusengine
    url: https://statusengine.org
```

> #external_url_lists:

Auch die `#` am Anfang muss weg, sonst ist es ein Kommentar der ignoriert wird

**Comment by tinoklauer** [comment]
Vielen Dank es hat Funktioniert =)

Den Parameter hatte ich aus https://github.com/statusengine/interface/issues/44 beim ersten Kommentar. Doch er bezog sich nicht auf die Statusengine.
