### ISSUE TITLE
Performance Graphs missing for node

### ISSUE THREAD

**Issue by duylong** [statusengine/interface#7]
Hi,

There is no performance graphs for node? In general we have only one graph, the PING.

**Comment by nook24** [comment]
Hi, yes Statusengine don't collect host/node performance data. 99% uses check_icmp as host check command and add a ping check as well as service.

**Comment by duylong** [comment]
Aaaah I thought it was collected because I saw "Performance data" in the node form:

```
Current state
    Up
State type
    Hard (1/3) 
Last status update
    11:35 16.09.2017
Last state change
    01:52 15.09.2017
Output
    PING OK - Packet loss = 0%, RTA = 0.05 ms
Performance data
    rta=0.054000ms;3000.000000;5000.000000;0.000000 pl=0%;80;100;0
Last check
    11:35 16.09.2017
Next check
    11:36 16.09.2017
Check interval
    1
Check period
```

It does not matter, I would add an extra check if needed.
